name: Publish Docker image (arm64)

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false
  schedule:
    - cron: 0 0 * * *

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Clone External Repo
        uses: actions/checkout@v3
        with:
          repository: Calcium-Ion/new-api
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Save version info
        run: |
          git fetch --tags
          echo "VERSION=$(git describe --tags --always)" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: install jq
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq

      - name: Get the latest tag.
        id: get-latest-tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/Calcium-Ion/new-api/tags | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Publish and build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            happyfools/new-api:latest
            happyfools/new-api:${{ env.LATEST_TAG }}